version: 2
jobs:
  build:
    docker:
      - image: python:3-slim
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./slack-vrc/requirements.txt -t ./slack-vrc/sp
            pip install ./slack-vrc/vrchat-api-python-master -t ./slack-vrc/sp
            pip install -r ./slack-vrc/requirements.txt -t ./slack-vrc/fsf
            pip install ./slack-vrc/vrchat-api-python-master -t ./slack-vrc/fsf
      - run:
          name: Compress *_lambda_upload.zip
          command: |
            apt-get update
            apt-get install -y zip
            cd slack-vrc/sp
            chmod 755 ./* -R
            mkdir -p /tmp/workspace
            zip -r /tmp/workspace/sp *
            cd ../fsf
            chmod 755 ./* -R
            zip -r /tmp/workspace/fsf *
      - store_artifacts:
          path: /tmp/workspace/sp.zip
          destination: sp_lambda_upload.zip
      - store_artifacts:
          path: /tmp/workspace/fsf.zip
          destination: fsf_lambda_upload.zip
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - sp.zip
            - fsf.zip
  release:
    docker:
      - image: python:3-slim
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install libraries
          command: |
            echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
            apt-get update
            apt-get -t stretch-backports install -y git golang
            export GOPATH=$HOME/go
            echo 'export PATH='"$GOPATH"'/bin:$PATH' >> $BASH_ENV
            go get github.com/tcnksm/ghr
      - run:
          name: Release
          command: |
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - hold
